[2023-02-16 09:26:42,283]-[Login.py]-[line:43]-ERROR: 获取cookie失败
[2023-02-16 09:31:06,830]-[Login.py]-[line:43]-ERROR: 获取cookie失败
[2023-02-16 09:35:59,894]-[Assert.py]-[line:17]-ERROR: 验证失败, 验证值为： 405, 结果为：200 
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\API_auto_test\common\Assert.py", line 14, in assert_equal
    assert value_1 == value_2
AssertionError
[2023-02-16 09:37:50,646]-[Assert.py]-[line:17]-ERROR: 验证失败, 验证值为： 405, 结果为：200 
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\API_auto_test\common\Assert.py", line 14, in assert_equal
    assert value_1 == value_2
AssertionError
[2023-02-16 09:39:45,524]-[Assert.py]-[line:17]-ERROR: 验证失败, 验证值为： 405, 结果为：200 
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\API_auto_test\common\Assert.py", line 14, in assert_equal
    assert value_1 == value_2
AssertionError
[2023-02-16 09:40:31,901]-[Assert.py]-[line:17]-ERROR: 验证失败, 验证值为： 9001, 结果为：200 
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\API_auto_test\common\Assert.py", line 14, in assert_equal
    assert value_1 == value_2
AssertionError
[2023-02-16 09:41:07,245]-[Assert.py]-[line:17]-ERROR: 验证失败, 验证值为： 9001, 结果为：200 
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\API_auto_test\common\Assert.py", line 14, in assert_equal
    assert value_1 == value_2
AssertionError
[2023-02-16 15:17:40,250]-[Assert.py]-[line:17]-ERROR: 验证失败, 验证值为： 9001, 结果为：200 
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\API_auto_test\common\Assert.py", line 14, in assert_equal
    assert value_1 == value_2
AssertionError
[2023-02-16 15:24:02,184]-[Assert.py]-[line:17]-ERROR: 验证失败, 验证值为： 9001, 结果为：200 
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\API_auto_test\common\Assert.py", line 14, in assert_equal
    assert value_1 == value_2
AssertionError
[2023-02-16 15:33:13,559]-[Assert.py]-[line:17]-ERROR: 验证失败, 验证值为： 9001, 结果为：200 
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\API_auto_test\common\Assert.py", line 14, in assert_equal
    assert value_1 == value_2
AssertionError
[2023-02-16 15:35:10,557]-[Assert.py]-[line:17]-ERROR: 验证失败, 验证值为： 9001, 结果为：200 
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\API_auto_test\common\Assert.py", line 14, in assert_equal
    assert value_1 == value_2
AssertionError
[2023-02-16 16:54:12,126]-[Request.py]-[line:33]-ERROR: Post请求接口：https://mrpa-test.ai-rtc.com:8082/plat/api/robot/list出错! request() got an unexpected keyword argument 'cookie'
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/API_auto_test/common/Request.py", line 30, in post_method
    response = requests.post(url=url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\clpytest\venv\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\clpytest\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'cookie'
[2023-02-16 16:56:08,788]-[Request.py]-[line:33]-ERROR: Post请求接口：https://mrpa-test.ai-rtc.com:8082/plat/api/robot/list出错! request() got an unexpected keyword argument 'cookie'
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/API_auto_test/common/Request.py", line 30, in post_method
    response = requests.post(url=url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\clpytest\venv\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\clpytest\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'cookie'
